name = "ttk-signal"
main = "src/index.ts"
compatibility_date = "2026-01-01"

routes = [{ pattern = "signal.dancingsnow.xyz", custom_domain = true }]

[durable_objects]
bindings = [{ name = "ROOMS", class_name = "SignalingRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]
